name: gfortran Compile
on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile with gfortran

    steps:

    - name: Install ubuntu dependencies
      run: |
        sudo apt-get install gfortran

    - name: Compile
      run: |
        cd $GITHUB_WORKSPACE/sandbox_fort/src
        gfortran -o a.out test.f90
