name: gfortran Compile and Run
on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile with gfortran and run

    steps:

    - name: Install ubuntu dependencies
      run: |
        sudo apt-get install gfortran

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: sandbox_fort

    - name: Compile
      run: |
        cd $GITHUB_WORKSPACE/sandbox_fort/src
        gfortran -o a.out test.f90

    - name: Run executable
      run: |
        cd $GITHUB_WORKSPACE/sandbox_fort/s
        ls -l
        ./a.out
