name: gfortran Compile and Run
on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile with gfortran and run

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: sandbox_fort

    - name: Cache Sandbox build
      id: cache-sandbox
      uses: actions/cache@v2
      with:
        path: ~/bin
        key: sandbox-20211119-${{ runner.os }}-gnu

    - name: Build 
      if: steps.cache-sandbox.outputs.cache-hit != 'true'
      run: |
        cd $GITHUB_WORKSPACE/sandbox_fort/src
        gfortran -o a.out test.f90
        mkdir -p ~/bin
        cp a.out ~/bin/.

    - name: Run executable
      run: |
        cd ~/bin
        ./a.out
